### ISSUE TITLE
Suggests are returning non existing terms

### ISSUE THREAD

**Issue by chrschw** [Flowpack/Flowpack.SearchPlugin#24]
Is there any way to prevent this? Or should the elasticsearch query be changed?

**Comment by kdambekalns** [comment]
Can you give some details? Ideally something that can be reproduced with the Neos demo site?

**Comment by chrschw** [comment]
there were two reasons:

1. beacause suggest was not separating the different languages which was fixed now, so you can ignore this case

2. it found also the name of the workspace 'live' and return it as a suggest term.
I later found out it was cased by a missing Nodetypes.yaml configuration i added for my site package:

<pre>

'unstructured':
  properties:
    '__workspace':
      search:
        elasticSearchMapping:
          type: string
          index: not_analyzed
          include_in_all: false
</pre>
