### ISSUE TITLE
No AjaxSearch available

### ISSUE THREAD

**Issue by diu-daniel** [Flowpack/Flowpack.SearchPlugin#30]
Hi there,
the documentation mentions that this Plugin has an AjaxSearch available which can be triggered with the following GET url:

`{f:uri.action(action: 'index', controller: 'AjaxSearch', package: 'Flowpack.SearchPlugin', absolute: 1)}`

The problem is: The **AjaxSearch**-Controller doesn't contain an **index**-action!

I tried to change it to **search**-action, since that is the only action in that controller, but the action requires an node, but only gets an search-term if triggered by AJAX.

How exactly can I make the AjaxSearch working? Is there something I missed?

Please I need help and thanks in advance,
Daniel :)

**Comment by bwaidelich** [comment]
@kdambekalns sorry for the mention but you added this section to the readme back [then](https://github.com/Flowpack/Flowpack.SearchPlugin/commit/ec30d421793a9e3b7140c30fd9cb4ee3eeee32d7). Do you remember how that is supposed to work?

I gave it a quick shot with a blank 3.1 demo site, but there are some pieces missing it seems: https://gist.github.com/bwaidelich/50d61843e5273de3ba3f0b201a6a20e5

**Comment by akappler** [comment]
Hi, 
in the viewhelper for the ajaxSearch is an argument missing. The correct viewhelper is `f:uri.action(action: 'search', controller: 'AjaxSearch', package: 'Flowpack.SearchPlugin', arguments:{node:node}, absolute: 1)}` the node is needed for the context and the language. I'm currently updating the docu.

cheers!

**Comment by kdambekalns** [comment]
Thanks for investigating. My guess is: I never actually used that line from the documentation but simply typed it down as in "should work like that", originating from a general "get it documented" impulse.
