### ISSUE TITLE
Dependent on Flowpack.ElasticSearch.ContentRepositoryAdaptor

### ISSUE THREAD

**Issue by Duske** [Flowpack/Flowpack.SearchPlugin#8]
In [Suggestcontroller ](https://github.com/skurfuerst/Flowpack.SearchPlugin/blob/master/Classes/Flowpack/SearchPlugin/Controller/SuggestController.php) the `\Flowpack\ElasticSearch\ContentRepositoryAdaptor\ElasticSearchClient` is injected, but the dependency for this package is not mentioned.

Thus, it does not work if use _Flowpack.SimpleSearch.ContentRepositoryAdaptor_ instead of _Flowpack.ElasticSearch.ContentRepositoryAdaptor_.
Is this correct or am I missing something?

**Comment by dlubitz** [comment]
+1

**Comment by dlubitz** [comment]
Anything new here? The dependency still exists and make it not possible to use this plugin with `Flowpack.ElasticSearch.ContentRepositoryAdaptor`. I will create a PR, but not sure ATM, how to solve.
Interface instead of usage of `ElasticSearchClient` directly?

**Comment by dlubitz** [comment]
For other one with same issue, you can exclude the class from flow object management in your Settings.yaml:

```
TYPO3:
  Flow:   
    object:
      excludeClasses:
        'Flowpack.SearchPlugin': ['Flowpack\\SearchPlugin\\Controller\\SuggestController']

**Comment by kdambekalns** [comment]
Solved by now…
